FROM node:21.7.3-alpine3.19@sha256:e4a06f554fd611cc44275c756452ee18aa2e475fd04da86a795a9e865743c51d

VOLUME ["/web/node_modules"]

VOLUME ["/web"]

WORKDIR /web

CMD ["sh", "-c", "npm ci; npm run build; node dist/src/index.js"]
