FROM node:22.13.1@sha256:ae2f3d4cc65d251352eca01ba668824f651a2ee4d2a37e2efb22649521a483fd

VOLUME ["/web/node_modules"]

VOLUME ["/web"]

WORKDIR /web

CMD ["sh", "-c", "npm ci; npm run build; node dist/src/index.js"]
