FROM node:iron-alpine@sha256:784d5a31b1158975352e257f64080db67431f565771606417851785d39124b25

VOLUME ["/web/node_modules"]

VOLUME ["/web"]

WORKDIR /web

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
        curl

CMD ["sh", "-c", "npm ci; npm run release; node dist/src/index.js"]
