catalogs:
  default:
    eslint: "10.6.0"
    vite: "8.1.0"
allowBuilds:
  unrs-resolver: false
overrides:
  "@codecov/vite-plugin>vite": "catalog:default"
  "eslint-config-love>eslint": "catalog:default"
  "eslint-plugin-import>eslint": "catalog:default"
